export const products = [
    {id: 1, categoria: "torta", title:"Letter / Number cakes", stock: 3 ,desciption:"Torta de chocolate y dulce de leche", price:"Precio a cotizar", imgDesc: "", imgUrl:"https://lh3.googleusercontent.com/DUt1_juI8ediN5rdh7RwwP9SJmWtJFtBC3FA3n8SLfdJoh58Uu7gQ874YX6fbc-0z1Ws7xCeFhNkv2-3VWAZCvkX9WvHLtzpiPon1uOFLuOhgqmpbOrd5u9HJBGiYA43xNzDntw0ypk=w2400"},
    {id: 2, categoria: "torta", title:"Tortas clásicas rellenas", stock: 3 , desciption:"Torta de chocolate y dulce de leche", price:"Precio a cotizar", imgDesc: "", imgUrl:""},
    {id: 3, categoria: "torta", title:"Tortas a pedido", stock: 3 , desciption:"Torta de chocolate y dulce de leche", price:"Precio a cotizar", imgDesc: "", imgUrl:"https://lh3.googleusercontent.com/wpFDNuWvWMnse-wblfED9wfQfeYQrvB8ne7kwh7EEMT0QyFd1Xn-gfbNn8byS7U3njgfe7wkQx-zOUYlrcyvak7gauzjo4m7E7uj_ZCymq0nSrQHMl_t4LaInndN-cBSlH3u7C8qFw4=w2400"},
    
    {id: 4, categoria: "desayuno", title:"¡Feliz Cumple!", stock: 3 , desciption:"Torta de chocolate y dulce de leche", price:"Precio a cotizar", imgDesc: "", imgUrl:""},
    {id: 5, categoria: "desayuno", title:"Las Alba", stock: 3 , desciption:"Torta de chocolate y dulce de leche", price:"Precio a cotizar", imgDesc: "", imgUrl:""},
    {id: 6, categoria: "desayuno", title:"Desayuno clásico", stock: 3 , desciption:"Torta de chocolate y dulce de leche", price:"Precio a cotizar", imgDesc: "", imgUrl:""},
    {id: 7, categoria: "desayuno", title:"Box Merienda", stock: 3 , desciption:"Torta de chocolate y dulce de leche", price:"Precio a cotizar", imgDesc: "", imgUrl:"https://lh3.googleusercontent.com/2t6m_IE-5aiXqn-zhdUQJ4smt0lPMQi3LBQkFF-ebTIxB0noU4w76pEKbGXawtE_kL72BnoqVtoz1oNvnOmhZN_5pEeeeRI3yAoASpRkmu_C2hJX4CaTXKxt0tI8PCshq-sxo_r67mA=w2400"},
    {id: 8, categoria: "desayuno", title:"Infantil", stock: 3 , desciption:"Torta de chocolate y dulce de leche", price:"Precio a cotizar", imgDesc: "", imgUrl:""},

    {id: 9, categoria: "tartas", title:"Lemon Pie", stock: 3 , desciption:"Torta de chocolate y dulce de leche", price:1300, imgDesc: "", imgUrl:"https://lh3.googleusercontent.com/TlLHrDj_nXJbOxhKnWR6zNDHzdMLSqSLI4zFGTc7mL92gR9mGdjERX0OEIxONEbkOXmEt5Oz19GdJ3aIpV8-uFJGDUPpTj2pm6qnbFUQfOa64XNaKABVxoOj_wHEgX1bka6vFVTahwY=w2400"},
    {id: 10, categoria: "tartas", title:"Tarta Cabsha", stock: 3 , desciption:"Torta de chocolate y dulce de leche", price:950, imgDesc: "", imgUrl:""},
    {id: 11, categoria: "tartas", title:"Tarta Frutillas", stock: 3 , desciption:"Torta de chocolate y dulce de leche", price:1400, imgDesc: "", imgUrl:""},
    {id: 12, categoria: "tartas", title:"Key Lemon Pie", stock: 3 , desciption:"Torta de chocolate y dulce de leche", price:1300, imgDesc: "", imgUrl:"https://lh3.googleusercontent.com/nwffR01BPE1S3N8yXWTxWCjd-qup4PBTLns8fMnlS0_v7mFYubCv6E9dwQbPp02LS4A7kfhETx63oZz9WByMXxpsotGOqVDAah-aMfZftPq0FSt6scyfYuf3FYzmYXOp5PukcUH4qpQ=w2400"},
    {id: 13, categoria: "tartas", title:"Chocotorta", stock: 3 , desciption:"Torta de chocolate y dulce de leche", price:1600, imgDesc: "", imgUrl:""},
    {id: 14, categoria: "tartas", title:"Mix Frutal", stock: 3 , desciption:"Torta de chocolate y dulce de leche", price:1400, imgDesc: "", imgUrl:"https://lh3.googleusercontent.com/RN_V8PU0ZWDc1wAVx8MMpn7TVbM99LYHwyngK9DHwnAimRvGK91mVlC-xIJXvP_NQEo5woZy0P-IyoBLvpGgqrU8PZ6ACjj9NrFvZ__Lr8VNcQPihxjfVoHVWjhJ7ha4JBlaylGGZlQ=w2400"},
    {id: 15, categoria: "tartas", title:"Chocooreo", stock: 3 , desciption:"Torta de chocolate y dulce de leche", price:1650, imgDesc: "", imgUrl:""},
    {id: 16, categoria: "tartas", title:"Coco y dulce de leche", stock: 3 , desciption:"Torta de chocolate y dulce de leche", price:1100, imgDesc: "", imgUrl:""},
    {id: 25, categoria: "tartas", title:"Matilda", stock: 3 , desciption:"Torta de chocolate y dulce de leche", price:2000, imgDesc: "", imgUrl:"https://lh3.googleusercontent.com/ttlSMk8eNmCXbkdgQTmriuz0uch1qpG_1cCbDcbsJOjSus3jn2-Eios5oixm4igVgjqWMoi_tbzUjEqaKW95DGrWOhTWeQ5LFd5WtreJGjBnk5F4SQBZe0XLcuzgL4rvJvmq166_b-o=w2400"},
    {id: 26, categoria: "tartas", title:"Brownie con Frutilla", stock: 3 , desciption:"Torta de chocolate y dulce de leche", price:1400, imgDesc: "", imgUrl:"https://lh3.googleusercontent.com/uO_G201bR5-ymu3Sx8PWSw-zyQ9fmaz0ZjClmxCQ5Wv5h2QvAuBOdyQz4mgjcrt2oqKWf04hjytuqs5ATTu0LIU4Onzaa5Jyd_t-Wqd7S_CKt-KBSqR11_Q49r1gEYH3RC3XNCEU-Xs=w2400"},
    {id: 27, categoria: "tartas", title:"Cheesecake", stock: 3 , desciption:"Torta de chocolate y dulce de leche", price:2000, imgDesc: "", imgUrl:"https://lh3.googleusercontent.com/bNqm5JQ2kGAT6KlLTdmw8-uMupwwoxCLH1mPrbiyS8lS4KQw-bjcvTxQfCDTxIUYNjfytzCld5BcAfrPhAKihaZXPwwgRdBs6893Vaih4acYJA6oRxzC6itx-sJPsitZddTZushX1g4=w2400"},
    {id: 28, categoria: "tartas", title:"Brownie con Frutos Rojos", stock: 3 , desciption:"Torta de chocolate y dulce de leche", price:1400, imgDesc: "", imgUrl:"https://lh3.googleusercontent.com/YN_J7fnvqiAECa0RNkJJB2A0Gc0MIxfW-LwDMpB4p5r_j2A9lgxg7Hxg5gkQ0_eNwqVoqSknQKNdKe2tnk0XMohcImNGGLGJocbUzdovlTMlAn0HXl9sSp6SaO-H_-PoMnFzb1Vx6PA=w2400"},
    {id: 29, categoria: "tartas", title:"Mousse Chocoblanco con Frutos Rojos", stock: 3 , desciption:"Torta de chocolate y dulce de leche", price:1800, imgDesc: "", imgUrl:"https://lh3.googleusercontent.com/GNu1kFCTPkZWicHTxyi456PPpGp5ZaDvn_1sEwz_6_vpjqZjpGCfmt7kMd73-C3LJv85IKLvGQfglIaQ0caO2LWrERD-dNhNwu3WMmgljjXeGhpWHzOhyibmnZaNzf9U7FPJmvZ6qhE=w2400"},
    {id: 30, categoria: "tartas", title:"Rogel", stock: 3 , desciption:"Torta de chocolate y dulce de leche", price:1500, imgDesc: "", imgUrl:"https://lh3.googleusercontent.com/rNQGzRKaDo6qXwiQ7zkoxnEMdotUxZq3u1qe45InbR7_-zEgr7U-Ogxg9w57CKF-vU3ii2e_IxqSkc7SQX8mxGUT8Na-_aQbICx2tGnksHILtwLVEQ3PNVgWnPfJH3y-Chn8aycoEOU=w2400"},

    {id: 17, categoria: "pasteleria", title:"Alfajores", stock: 3 , desciption:"Torta de chocolate y dulce de leche", price:650, imgDesc: "", imgUrl:"https://lh3.googleusercontent.com/o79xEBYwOnQ8_-kslJ7QwcHcFPj-8ZkNn003EbYX3FN4ozWG3Wd92QgNosnRYzGTv70wkEU5w8OiirRpPfmVWmza6486ugrRzLygWQEGPhZw0XdXQdJZ6pE1xxAELnAP6i3AtbnIBVU=w2400"},
    {id: 18, categoria: "pasteleria", title:"Macarons", stock: 3 , desciption:"Torta de chocolate y dulce de leche", price:380, imgDesc: "", imgUrl:""},
    {id: 19, categoria: "pasteleria", title:"Lingotes", stock: 3 , desciption:"Torta de chocolate y dulce de leche", price:350, imgDesc: "", imgUrl:"https://lh3.googleusercontent.com/DqNKY0KLmPvY-xN9kn5NSKnxOJKgWECV2nlArcgdvZRqxZ0QeJQSBWQvNUjhzWjDrQBwy9mxKbNit1ptBaOYuLE1VihrqSx46wtOqzjs7Dwl01cp4jN0VY36ixSQGqxrtkKRTPfxN8Y=w2400"},
    {id: 20, categoria: "pasteleria", title:"Profiteroles", stock: 3 , desciption:"Torta de chocolate y dulce de leche", price:540, imgDesc: "", imgUrl:""},
    {id: 21, categoria: "pasteleria", title:"Cookies Decoradas", stock: 3 , desciption:"Torta de chocolate y dulce de leche", price:90, imgDesc: "", imgUrl:""},
    {id: 22, categoria: "pasteleria", title:"Cuadrados dulces", stock: 3 , desciption:"Torta de chocolate y dulce de leche", price:80, imgDesc: "", imgUrl:"https://lh3.googleusercontent.com/Cn6xbaj9wohMqEMd-P_rjva05xFpAgA5cK-L7nWOHovlGJ5evi7Hm_yeswmJiJA6a5RIRvHReZg75EWsl5WO6cLQlBYIrYoMImKfUG5A6Qr9bQIyokZ3FxmxAEsB4yYBxEcZQj59VbQ=w2400"},
    {id: 27, categoria: "pasteleria", title:"Cupcakes", stock: 3 , desciption:"Torta de chocolate y dulce de leche", price:90, imgDesc: "", imgUrl:"https://lh3.googleusercontent.com/ct8jFMJRd-1q0bGBivnLoQfgiMq5NIFWu2-dp2_F2-g-zr1XvrrNu4ApnAYAGB2RJWz9d2zPX6OZy3K-KTQHnD_3idFssyVvOQSa89SIRpCm2efYSmxWGtdElyDH8FVKB5UWIL0XrvA=w2400"},

    {id: 23, categoria: "eventosEsp", title:"Mesas dulces", stock: 3 , desciption:"Torta de chocolate y dulce de leche", price:"Precio a cotizar", imgDesc: "", imgUrl:""},
    {id: 24, categoria: "eventosEsp", title:"Fechas Especiales", stock: 3 , desciption:"Torta de chocolate y dulce de leche", price:"Precio a cotizar", imgDesc: "", imgUrl:""},

];